### ISSUE TITLE
tyk folder

### ISSUE THREAD

**Issue by Xroute53** [zalbiraw/tyk-docker-simple-node-api#1]
hi team,

I don't see the tyk folder in the repo, please help guide me. Thanks
-Sandeep

**Comment by sedkis** [comment]
> hi team,
> 
> I don't see the tyk folder in the repo, please help guide me. Thanks -Sandeep

Hey,

that's what the [script](https://github.com/TykTechnologies/tyk-docker-simple-node-api/blob/main/scripts/init.sh) does, it installs all the necessary files.

Please follow the README to get started.  Thanks!

**Comment by Xroute53** [comment]
hey @sedkis I just figured that the script fails to copy those files as the npx fails. Sorry my bad. Thanks
